# icono del prompt
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

# directorio
[directory]
style = "blue bold"
read_only = " ğŸ”’"

# git
[git_branch]
symbol = "ğŸŒ± "
style = "yellow"

[git_status]
style = "red"
modified = "ğŸ“ "
deleted = "âŒ "
staged = '[++\($count\)](green)'
untracked = '[?](cyan)'


[username]
disabled = false
format = "ïŒš [$user]($style_user) " 
style_user = "bold green"
show_always = true

[time]
disabled = false
format = "ğŸ•™ [$time]($style) "
time_format = "%H:%M"  # 24h formato
style = "bold yellow"


